[package]
name = "itired"
version = "1.0.2"
description = "iTired Music Player"
authors = ["iTired"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "itired_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
strip = true
lto = true
opt-level = "s"
codegen-units = 1
